<br>
# Reading and Writing CSV files

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [1]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [2]:
len(mpg)

234

<br>
`keys` gives us the column names of our csv.

In [3]:
mpg[0]

{'': '1',
 'manufacturer': 'audi',
 'model': 'a4',
 'displ': '1.8',
 'year': '1999',
 'cyl': '4',
 'trans': 'auto(l5)',
 'drv': 'f',
 'cty': '18',
 'hwy': '29',
 'fl': 'p',
 'class': 'compact'}

In [4]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [5]:
mpg[0].values()

dict_values(['1', 'audi', 'a4', '1.8', '1999', '4', 'auto(l5)', 'f', '18', '29', 'p', 'compact'])

<br>
This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [6]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [7]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

<br>
Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [8]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

<br>
Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [11]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, cyltypecount, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[2])
CtyMpgByCyl

[('8', 70, 12.57), ('6', 79, 16.22), ('5', 4, 20.50), ('4', 81, 21.01)]

In [ ]:
for i in cars 
    write down cty, cyl some where
    
    
take average based on cyl 

In [ ]:
for j in cyl (4, 5, 6, 8)
    count = 0
    for i in cars
        if (i'th cyl == j) 
            sum cty
            count +=1
            
    divide sum/count
    

<br>
Use `set` to return the unique values for the class types in our dataset.

In [12]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

<br>
And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [14]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # 
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, vclasscount, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[2])
HwyMpgByClass

[('pickup', 33, 16.88),
 ('suv', 62, 18.13),
 ('minivan', 11, 22.36),
 ('2seater', 5, 24.80),
 ('midsize', 41, 27.29),
 ('subcompact', 35, 28.14),
 ('compact', 47, 28.30)]

<br>
# The Python Programming Language: Dates and Times

In [15]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [16]:
tm.time()

1699099935.57

<br>
Convert the timestamp to datetime.

In [20]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2023, 11, 4, 15, 12, 53, 818698)

<br>
Handy datetime attributes:

In [21]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2023, 11, 4, 15, 12, 53)

<br>
`timedelta` is a duration expressing the difference between two dates.

In [22]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

<br>
`date.today` returns the current local date.

In [23]:
today = dt.date.today()
today

datetime.date(2023, 11, 4)

In [24]:
today - delta # the date 100 days ago

datetime.date(2023, 7, 27)

In [25]:
today > today-delta # compare dates

True

<br>
# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

In [26]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [28]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} lives in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks lives in Ann Arbor, MI, USA and works in the department School of Information


<br>
Here's an example of mapping the `min` function between two lists.

In [29]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)

In [30]:
cheapest

<br>
Now let's iterate through the map object to see the values.

In [31]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [32]:
my_function = lambda a, b, c : a + b

In [33]:
my_function(1, 7, 3)

8

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [34]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
Now the same thing but with list comprehension.

In [35]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [36]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [37]:
mylist = [1, 2, 3]
mylist

[1, 2, 3]

In [38]:
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [39]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [40]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [41]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [42]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [43]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [44]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br>
`resize` changes the shape and size of array in-place.

In [45]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [46]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [47]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [48]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [49]:
y

array([4, 5, 6])

In [50]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>
Create an array using repeating list (or see `np.tile`)

In [51]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [52]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [58]:
import time
import numpy as np

size_of_vec = 1000000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    #print(X, Y, Z)
    return time.time() - t1


In [59]:
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    #print(X, Y, Z)
    return time.time() - t1


In [65]:
t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.33270955085754395 0.008976459503173828
Numpy is in this example 37.06467463479416 faster!


<br>
#### Combining Arrays

In [68]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [69]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [70]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [71]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [72]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [73]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [74]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [77]:
z = np.array([y, y**2])
print(z)
print(len(z[0])) # number of rows of array

[[ 4  5  6]
 [16 25 36]]
3


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [78]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [80]:
z.shape

(2, 3)

<br>
Use `.T` to get the transpose.

In [79]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [81]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [82]:
z.dtype

dtype('int32')

<br>
Use `.astype` to cast to a specific type.

In [83]:
z = z.astype('f')
z.dtype
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [84]:
a = np.array([-4, -2, 1, 3, 5]) 

In [85]:
a.sum()

3

In [86]:
a.max()

5

In [87]:
a.min()

-4

In [88]:
a.mean()

0.6

In [89]:
a.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [90]:
a.argmax()

4

In [91]:
a.argmin()

0

<br>
## Indexing / Slicing

In [92]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [93]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [94]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

<br>
Use negatives to count from the back.

In [95]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [96]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

<br>
Let's look at a multidimensional array.

In [97]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [98]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns

In [99]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [100]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [101]:
r[-1, ::2]

array([30, 32, 34])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [102]:
r[r > 27]

array([28, 29, 30, 31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [104]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [105]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [106]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [107]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [108]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [109]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [110]:
test = np.random.randint(0, 10, (4,3))
test

array([[9, 7, 7],
       [0, 1, 3],
       [8, 5, 2],
       [3, 8, 9]])

<br>
Iterate by row:

In [111]:
for row in test:
    print(row)

[9 7 7]
[0 1 3]
[8 5 2]
[3 8 9]


<br>
Iterate by index:

In [112]:
for i in range(len(test)):
    print(test[i])

[9 7 7]
[0 1 3]
[8 5 2]
[3 8 9]


<br>
Iterate by row and index:

In [113]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [9 7 7]
row 1 is [0 1 3]
row 2 is [8 5 2]
row 3 is [3 8 9]


<br>
Use `zip` to iterate over multiple iterables.

In [114]:
test2 = test**2
test2

array([[81, 49, 49],
       [ 0,  1,  9],
       [64, 25,  4],
       [ 9, 64, 81]], dtype=int32)

In [115]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[9 7 7] + [81 49 49] = [90 56 56]
[0 1 3] + [0 1 9] = [ 0  2 12]
[8 5 2] + [64 25  4] = [72 30  6]
[3 8 9] + [ 9 64 81] = [12 72 90]
